---

- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove unwanted dependencies.
  become: yes
  apt:
    autoremove: yes

- name: install node and npm dependencies.
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2. #sudo npm install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: 'extract artifact'
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: start app
  become: yes
  shell: |
    pm2 start npm --start




    
